#!/bin/bash

. rabot-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-utils" >&2
  exit 1
fi

function showHelp
{
cat << DOCSTRING
Usage: $(basename "$0") [DIR]

'$(basename "$0")' prints the documentation of all executable files found in a given
directory tree DIR or, by default, in the Current Working Directory (CWD).
First the contents of a file 'DIR/readme-head.rst' (if it exists) are printed to
stdout. Then every executable file in DIR is called with the option '--help' and
additional reStructuredText markup is added to the output. Finally, the contents of
a file 'DIR/readme-tail.rst' (if it exists) are printed to stdout.

Example:

Create a README file in reStructuredText format, documenting all scripts in the CWD:

    $ docScripts > README.rst
DOCSTRING
}

checkForHelp $1

directory=${1:-$PWD}
try cd $directory

headFile="readme-head.rst"
if [ -f "$headFile" ]; then
    cat "$headFile"
    echo
fi

allHelp .

tailFile="readme-tail.rst"
if [ -f "$tailFile" ]; then
    cat "$tailFile"
    echo
fi
