#!/bin/bash

. rabot-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-utils" >&2
  exit 1
fi

function showHelp
{
cat << DOCSTRING
Usage: $(basename "$0") ['find' arguments]

'$(basename "$0")' is similar to 'fnd' but adds a '-print0' option to
the 'find' command.

For more info, see 'fnd --help'.
DOCSTRING
}

checkForHelp $1

require find

names=".git .svn .hg .bzr CVS"
expression=

while read name; do
   expression="$expression ""! -path */$name ! -path */$name/*"
done < <(tr ' ' $'\n' <<< "$names")

find $* $expression -print0
