#!/bin/bash

. rabot-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-utils" >&2
  exit 1
fi

function showHelp
{
cat << DOCSTRING
Usage:
    first form:
        $(basename "$0") COMMAND [ARG1]...

    second form:
        COMMAND [ARG1]... | $(basename "$0")

In the first form, '$(basename "$0")' invokes the command string and sends
its output (both stdout and stderr) to two different targets: stdout and a
logfile.

In the second form, the stdout of the command is piped to '$(basename "$0")',
where it is duplicated over stdout and a logfile. If you want to log stderr
too, redirect it to stdout first, like this:

    COMMAND [ARG1]... 2>&1 | $(basename "$0")

In addition to passing on the output of the command, '$(basename "$0")'
adds a header and a footer section with supplementary information. If the
second form is used however, this information will not contain the command
string that has been invoked nor the exit status of the command.

The logfile is saved in the directory '~/log' by default. This can be
overridden by setting the environment variable RABOT_LOGDIR to an appropriate
value. If the directory doesn't exist, it will be created.

The filename of the logfile has the following form:

    YYYYMMDDhhmmss_RND.txt

The part before the extension is the current time and a random alphanumerical
string, as explained in 'timestamp-id --help'.

In the log directory a symbolic link called 'latest' will be created or updated
pointing to the newly created logfile.

Examples:

A minimal sample of the first form:

    user@host ~ $ logop echo Hello
    ==== Start log: 2014-05-23 22:31:09
    ==== Logscript: /home/user/tools/rabot/logop/logop
    ==== Command: echo Hello
    ==== Working directory: /home/user
    ==== Logfile: /home/user/log/20140523223109_f4w.txt

    Hello

    ==== Exit status: 0
    ==== Elapsed: 0.00 seconds
    ==== End log: 2014-05-23 22:31:09

A minimal sample of the second form:

    user@host ~ $ echo Hello | logop
    ==== Start log: 2014-05-23 22:34:24
    ==== Logscript: /home/user/tools/rabot/logop/logop
    ==== Working directory: /home/user
    ==== Logfile: /home/user/log/20140523223423_q5n.txt

    Hello

    ==== Elapsed: 0.00 seconds
    ==== End log: 2014-05-23 22:34:24

See also: 'logopd', 'logopf'
DOCSTRING
}

checkForHelp $1

require timestamp-id

logFile="$(newLogfile)"

. logopx $* 2>&1 > >(tee -a "$logFile")

exit $logopExitStatus
