#!/bin/bash

. rabot-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-utils" >&2
  exit 1
fi

function showHelp
{
cat << DOCSTRING
Usage:
    first form:
        $(basename "$0") DIR COMMAND [ARG1]...

    second form:
        COMMAND [ARG1]... | $(basename "$0") DIR

The behavior of '$(basename "$0")' is similar to 'logop', with the
following differences:

- An extra 'DIR' argument will set a custom log directory.

- As a result, the symlink called 'latest.txt' is created/updated
  in 'DIR' instead of the log directory established by 'logop'.

For more info, see: 'logop --help'

A minimal sample of the first form:

    user@host ~ $ logopd mylogdir echo Hello
    ==== Start log: 2014-05-23 22:37:40
    ==== Logscript: /home/user/tools/rabot/logop/logopd
    ==== Command: echo Hello
    ==== Working directory: /home/user
    ==== Logfile: /home/user/mylogdir/20140523223740_8yo.txt

    Hello

    ==== Exit status: 0
    ==== Elapsed: 0.00 seconds
    ==== End log: 2014-05-23 22:37:40

A minimal sample of the second form:

    user@host ~ $ echo Hello | logopd mylogdir
    ==== Start log: 2014-05-23 22:38:17
    ==== Logscript: /home/user/tools/rabot/logop/logopd
    ==== Working directory: /home/user
    ==== Logfile: /home/user/mylogdir/20140523223817_0r0.txt

    Hello

    ==== Elapsed: 0.00 seconds
    ==== End log: 2014-05-23 22:38:17

See also: 'logop', 'logopf'
DOCSTRING
}

checkForHelp $1

require logop

export logDir=$1
shift
. logop $*
