#!/bin/bash

. rabot-common
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-common" >&2
  exit 1
fi

checkForHelp $1

: << DOCSTRING
Usage: $(basename "$0") [LENGTH]

'$(basename "$0")' prints a random alphanumerical string of
LENGTH characters (3 by default).

Example:

    user@host ~ $ randid 5
    mx2ft
DOCSTRING

idLength=${1:-3}
if [ "$idLength" -gt "0" ]; then
    cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w $idLength | head -n 1
fi
