#!/bin/bash

. rabot-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-utils" >&2
  exit 1
fi

require tar

xdir_this=tgz
xdir_other=zip

. xdir

tar -cpzf "$destFile" "$srcDirRelative"
exitOnError "The command 'tar -cpzf $destFile $srcDirName' returned an error"

readlink -f "$destFile"
