#!/bin/bash

. rabot-common
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-common" >&2
  exit 1
fi

require tar

xdir_this=tgz
xdir_other=zip

. xdir-core

tar -cpzf "$destFile" "$srcDirRelative"
exitOnError 1 "The command 'tar -cpzf $destFile $srcDirName' returned an error"

readlink -f "$destFile"
