#!/bin/bash

. rabot-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-utils" >&2
  exit 1
fi

function showHelp
{
cat << DOCSTRING
Usage: $(basename "$0")

'$(basename "$0")' will print the current time plus a
3-character random alphanumerical string in the following way:

    YYYYMMDDhhmmss_RND

where 'YYYYMMDDhhmmss' is the timestamp (produced by 'fullts')
and 'RND' is the random string (produced by 'randid').

Example:

    user@host ~ $ timestamp-id
    20140328133629_1oy

See also: 'fullts', 'randid'
DOCSTRING
}

checkForHelp $1

require fullts
require randid

echo "$(fullts)_$(randid)"

