#!/bin/bash

. rabot-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-utils" >&2
  exit 1
fi

function showHelp
{
cat << DOCSTRING
Usage: $(basename "$0") DIR COMMAND [ARG1]...

'$(basename "$0")' performs COMMAND with its arguments in
every directory of the tree rooted in DIR.

Example:

    user@host / $ $(basename "$0") ~ pwd
    /home/user
    /home/user/mydir
    /home/user/myotherdir
DOCSTRING
}

checkForHelp $1
minNumArgs 1 $#

cd "$1"
exitOnError "walkdir : Could not 'cd' into $1"
shift

while read dir; do
    pushd "$dir" > /dev/null
    "$*"
    popd > /dev/null
done < <(find . -type d)
