#!/bin/bash

. rabot-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-utils" >&2
  exit 1
fi

require zip

xdir_this=zip
xdir_other=tgz

. xdir-core

zip -rq "$destFile" "$srcDirRelative"
exitOnError 1 "The command 'zip -rq $destFile $srcDirName' returned an error"

readlink -f "$destFile"
